# Generated by Django 3.1 on 2020-12-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201115_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='assignment',
            name='consommation',
            field=models.IntegerField(default=0),
        ),
    ]
