# Generated by Django 3.1 on 2020-12-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20201211_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='consommation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
