# Generated by Django 3.1 on 2020-12-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20201211_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='consommation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
