# Generated by Django 3.1 on 2020-12-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20201214_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='consommation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
