# Generated by Django 3.1 on 2020-12-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20201214_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='consommation',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
