# Generated by Django 3.2.5 on 2021-08-09 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20201214_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('consommation', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
        ),
        migrations.DeleteModel(
            name='assignment',
        ),
    ]
